"""add service tracking fields

Revision ID: f4d2821df3e2
Revises: 0987006a4f07
Create Date: 2025-09-28 18:13:29.730606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4d2821df3e2'
down_revision = '0987006a4f07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_a_service_hand', sa.Integer(), nullable=True, default=1))
        batch_op.add_column(sa.Column('team_b_service_hand', sa.Integer(), nullable=True, default=1))
        batch_op.add_column(sa.Column('team_a_max_consecutive', sa.Integer(), nullable=True, default=0))
        batch_op.add_column(sa.Column('team_b_max_consecutive', sa.Integer(), nullable=True, default=0))
        batch_op.add_column(sa.Column('current_serving_team', sa.String(length=1), nullable=True, default='A'))
    
    # Update existing rows with default values
    op.execute("UPDATE sets SET team_a_service_hand = 1 WHERE team_a_service_hand IS NULL")
    op.execute("UPDATE sets SET team_b_service_hand = 1 WHERE team_b_service_hand IS NULL")
    op.execute("UPDATE sets SET team_a_max_consecutive = 0 WHERE team_a_max_consecutive IS NULL")
    op.execute("UPDATE sets SET team_b_max_consecutive = 0 WHERE team_b_max_consecutive IS NULL")
    op.execute("UPDATE sets SET current_serving_team = 'A' WHERE current_serving_team IS NULL")
    
    # Now make columns NOT NULL
    with op.batch_alter_table('sets', schema=None) as batch_op:
        batch_op.alter_column('team_a_service_hand', nullable=False)
        batch_op.alter_column('team_b_service_hand', nullable=False)
        batch_op.alter_column('team_a_max_consecutive', nullable=False)
        batch_op.alter_column('team_b_max_consecutive', nullable=False)
        batch_op.alter_column('current_serving_team', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sets', schema=None) as batch_op:
        batch_op.drop_column('current_serving_team')
        batch_op.drop_column('team_b_max_consecutive')
        batch_op.drop_column('team_a_max_consecutive')
        batch_op.drop_column('team_b_service_hand')
        batch_op.drop_column('team_a_service_hand')

    # ### end Alembic commands ###
